### ISSUE TITLE
Initial Conception

### ISSUE THREAD

**Issue by Cleop** [dwyl/tachyons-bootstrap#1]
See issue: https://github.com/dwyl/learn-tachyons/issues/9

Rebuild bootstrap using tachyons to create a super useful and beautiful standard components library!

**Comment by nelsonic** [comment]
@Cleop this is more of a _showcase_ for what we _can_ do with Tachyons 
and an _opportunity_ to _practice_ Tachyons skills 
as opposed to the library that _we_ @dwyl are going to use for our product(s),
but yeah, it will be "_super useful_"! 🎉

**Comment by Cleop** [comment]
Now the initial idea and details from the issue above have been added to the README by #4. Closing for this reason.
