### ISSUE TITLE
Create Bootstrap Typography section

### ISSUE THREAD

**Issue by Cleop** [dwyl/tachyons-bootstrap#21]
- [x] Create the Bootstrap Typography section using tachyons: http://getbootstrap.com/css/#type

**Comment by Cleop** [comment]
Bootstrap default for p tags is 14px, equivalent to f6 in tachyons however they apply it to the body and therefore throughout.

**Comment by Cleop** [comment]
Tachyons does not do justified text for accessibility reasons detailed here: https://github.com/tachyons-css/tachyons/issues/115
Leaving this out of the text alignment part.

**Comment by Cleop** [comment]
Help cursor is not in the main tachyons, but can be found separately here: https://github.com/mrmrs/css-cursors as `cursor-help`.

This is used in tachyons on the abbreviation examples.

**Comment by Cleop** [comment]
<img src="https://cloud.githubusercontent.com/assets/16775804/26580110/96b01e84-452e-11e7-857a-3847c5e2e916.png" width=150px />
The tachyons default is the top version, the bootstrap version looks like:
<img src="https://cloud.githubusercontent.com/assets/16775804/26580116/9e3d41ea-452e-11e7-9a94-97f1c5cd9376.png" width=40px />
You can apply tachyons text decoration `no-underline`, see: http://tachyons.io/docs/typography/text-decoration/ to try and remove the default however it doesn't work.
It removes one entry for text decoration but not the second like so: 
<img src="https://cloud.githubusercontent.com/assets/16775804/26580189/fdab6c6a-452e-11e7-8f74-9b35f4dff93f.png" width=180px />

**Comment by Cleop** [comment]
Blockquote options in bootstrap look like this:
<img src="https://cloud.githubusercontent.com/assets/16775804/26585584/6ed99316-4544-11e7-9aa7-92d5a7e5268e.png" width=300px />
However the `-` is achieved using a before:: pseudo element which we cannot use in plain tachyons. For now I will code it in.

**Comment by katbow** [comment]
merged in #28

**Comment by iteles** [comment]
Thanks!
