### ISSUE TITLE
Create Code section of Bootstrap

### ISSUE THREAD

**Issue by Cleop** [dwyl/tachyons-bootstrap#24]
- [x] Create the 'Code' section of Bootstrap using tachyons: http://getbootstrap.com/css/#code

**Subsections to do:**
* [x] Inline
* [x] User input
* [x] Basic block
* [x] Variables
* [x] Sample output

**Comment by katbow** [comment]
merged in #36

**Comment by iteles** [comment]
The wording here strikes me as odd: http://tachyons-bootstrap.dwyl.com/#code
<img width="806" alt="screen shot 2017-08-10 at 10 56 45" src="https://user-images.githubusercontent.com/4185328/29165452-a15f1d98-7dba-11e7-99da-e84a276ef228.png">

In bootstrap, it's using `<code>` that has an effect as per the text, but in tachyons-bootstrap, it's all the other classes. Could we update the text to reflect the reality please?

**Comment by Cleop** [comment]
@iteles - if I've understood your comment above correctly were you suggesting that the use of the `<code>` tag didn't make any difference? My understanding from https://developer.mozilla.org/en-US/docs/Web/HTML/Element/code is that it sets the font to monospace which the Tachyons classes do not, as aswell as being semantic/ good for screen readers etc.

Did I understand you correctly or were you talking about something else with the wording?
