### ISSUE TITLE
Reformat Bootstrap app without Phoenix

### ISSUE THREAD

**Issue by Cleop** [dwyl/tachyons-bootstrap#25]
To improve the accessibility of this resource, it is going to be stripped of Phoenix to compromise a more simple structure so that the focus is on the tachyons/styling and not the project set up/structure.

**Comment by Cleop** [comment]
@nelsonic, here: https://github.com/dwyl/learn-phoenix-framework/issues/81#issuecomment-303374085 you shared a proposed file structure featuring some templated files e.g. buttons, forms etc. to be rendered in the main layout file. 

Are you happy for us to use handlebars to achieve this or was there something else you'd envisaged?

**Comment by katbow** [comment]
merged in #27
