### ISSUE TITLE
Add accessibility pre-commit hook

### ISSUE THREAD

**Issue by iteles** [dwyl/tachyons-bootstrap#39]
As a product owner, I would like to make sure that everything in this component guide is _always_ accessible so that everyone is able access and use it.

## Acceptance Criteria
+ [x] Add a11y pre-commit hook (no need to spend time on adding it to CI just yet, see https://github.com/LDMW/app/pull/117)
+ [x] Run existing components through hook
+ [ ] Open issue to fix a11y issues if these exist

**Comment by Cleop** [comment]
And the current result:
![image](https://user-images.githubusercontent.com/16775804/34574885-b179cffa-f170-11e7-9deb-1b0c8a190a27.png)
At a glance I can see that some of these are things that have not been done as these things are demos and therefore maybe don't have context e.g. no alt text for an image like this:
<img src="https://user-images.githubusercontent.com/16775804/34574925-d43db5e2-f170-11e7-91df-5f524032ce5d.png" width=150px />
@iteles - do you think this should be a priority before launch?

**Comment by iteles** [comment]
I would like to sort out at least the most basic a11y issues - I'll run this and take a look

**Comment by iteles** [comment]
Closing this as now out of date.
