### ISSUE TITLE
Set up Google Analytics for subdomain

### ISSUE THREAD

**Issue by Cleop** [dwyl/tachyons-bootstrap#51]
- [x] Sets up Google Analytics for subdomain

Following this guide: http://www.verticalrail.com/kb/filter-in-google-analytics-to-track-subdomains/

- I've added the UA code script to the tachyons-bootstrap index.html ✅ 
- History: previously the GA are not picking up visits properly (see the graph below) and this seems to have coincided with the change from dwyl.io ▶️ dwyl.com. This has since been rectified ✅ 
- I've now created a new view for tachyons-bootstrap
- The guide now proposes creating a filter but I want to understand why I might need one so I create one that is useful for our needs.

I will have to wait until #50 is merged in before I can check that the analytics is working as the current live version doesn't feature the UA code script. Once #50 is merged I will test this but I believe the actions are in place for this to function.

**Comment by ghost** [comment]
@Cleop the site is hosted on .com
.io forwards to .com

Let me know if you have any specific questions around that

**Comment by Cleop** [comment]
@markwilliamfirth 
Our analytics has dropped drastically after May 9th, I think GA is tracking only .io ![image](https://user-images.githubusercontent.com/16775804/27235028-1e904d02-52b7-11e7-9d22-4c6ffef17e3e.png)

**Comment by ghost** [comment]
@cleop looking at the graph I'd say your assumption is most likely correct

**Comment by Cleop** [comment]
@iteles or @nelsonic do you know what the filter `prevent-exposing-token` does for the main dwyl site and do I need to replicate this for tachyons bootstrap? It looks like it's just checking for traffic to the dwyl site but I'm a bit thrown by the name and whether this infers something else.

Also, the guide I was following recommended putting your subdomain on your referral exclusion list so as not to skew self-referrals, however I believe that it will be useful for us to see whether traffic from tachyons-bootstrap navigates to dwyl.com - let me know if you feel otherwise.

**Comment by iteles** [comment]
I don't know the answer to your first question, though could google it. @danwhy is this something you've come across for LDMW?

**Comment by Danwhy** [comment]
I didn't come across this, but it looks like it's a filter that's there to exclusively show data from dwyl.com, meaning if another person were to steal your GA token, any traffic coming from their site would be ignored: https://blog.kissmetrics.com/protect-analytics-from-hacking/
If you're using the same tracking for multiple domains/subdomains you may need to modify the filter to include it, or create a new filter per domain

**Comment by Cleop** [comment]
Closing as now complete.

**Comment by iteles** [comment]
@cleop Worth adding a paragraph to learn-google-analytics?

**Comment by Cleop** [comment]
On it: https://github.com/dwyl/learn-google-analytics/issues/14
