### ISSUE TITLE
tachyonsbootstrap.com ?

### ISSUE THREAD

**Issue by ghost** [dwyl/tachyons-bootstrap#57]
<img width="703" alt="screen shot 2017-06-27 at 12 19 26" src="https://user-images.githubusercontent.com/5732209/27585141-f37e326c-5b32-11e7-8a8f-6544bd02e3c3.png">

**Comment by iteles** [comment]
@markwilliamfirth Let's:
+ [x] Buy it
+ [x] Redirect it to the dwyl sub-domain (the point being to introduce drive more traffic to our main site)
+ [ ] Make sure google analytics is picking it up so we know where our traffic is coming from

**Comment by Cleop** [comment]
@iteles - what url should be used/ referred to in the video?

**Comment by iteles** [comment]
I would go with the dwyl one - the intention is to drive traffic. Buying the other one is more about 'collecting' the internet real estate for this 👍

**Comment by nelsonic** [comment]
worth remembering that you aren't _buying_ anything. you're _renting_ it. i.e. adding to the cost ..
but ... if it gets SEO and is a good TLD then it _could_ be worth it.
What we need to do is _estimate_ the value vs. the cost.
@iteles how much are we paying for `.com` domain annual renewals?

**Comment by iteles** [comment]
@nelsonic £10ish. It's worth it if we track it for the first year and then make the call based on the data - which is why google analytics tracking is in the checklist above ;)

**Comment by ghost** [comment]
@iteles I tried to buy the domain on iwantmyname and your card was declined for some reason?

**Comment by iteles** [comment]
@markwilliamfirth It's probably just an old card, please just add your company card 👍

**Comment by ghost** [comment]
@iteles ok can we change the email to the hello / finance company email / my email? I don't get emails from the current email.

**Comment by ghost** [comment]
@iteles also probably a good idea to check whether your current card was declined or whether it actually was an old card

**Comment by ghost** [comment]
<img width="954" alt="screen shot 2017-06-28 at 13 18 00" src="https://user-images.githubusercontent.com/5732209/27636607-3fea6bbc-5c04-11e7-903e-c7c8b1a0d501.png">

@cleop it's forwarding now - do you know if any extra steps need to be done with regards to google analytics?

**Comment by Cleop** [comment]
@markwilliamfirth - I can't seem to get that page to load? Neither http://tachyonsbootstrap.com nor http://www.tachyonsbootstrap.com/

The analytics should work because it will still register a visit to the usual url once it's been forwarded. But first, I want to make sure I'm looking at the same link because I can't see these pages.

**Comment by ghost** [comment]
@cleop I have the same issues, but apparently it does still work

<img width="744" alt="screen shot 2017-07-13 at 15 24 32" src="https://user-images.githubusercontent.com/5732209/28171167-7ace23f4-67df-11e7-929b-a6fe0a01e7fe.png">

**Comment by ghost** [comment]
@Cleop works for me now 👍

**Comment by Cleop** [comment]
Analytics are successfully picking up these paths 👍 thanks @markwilliamfirth 

Happy to close this issue ✅
