### ISSUE TITLE
Review content throughout to make more tachyons/dwyl-like

### ISSUE THREAD

**Issue by iteles** [dwyl/tachyons-bootstrap#59]
As we are using tachyons, I would like to see the content of the examples be more tachyons/dwyl related as a nod to the creators of these components & tech.

e.g. http://tachyons-bootstrap.dwyl.com/#table

**Comment by Cleop** [comment]
Will go through and replace words (colours are already updated) where relevant but will only do so where it does not detract from the meaning/understanding. I'm not going to replace Lorem Ipsum in case people don't understand why the text is there.

- Replaced lists, names, handles, emails etc.

**Comment by iteles** [comment]
:tada:
