### ISSUE TITLE
Does Tachyons normalise browser css?

### ISSUE THREAD

**Issue by digvijay-upadhyay** [dwyl/tachyons-bootstrap#63]
Does Tachyons normalise browser css or do I need to use some other normalising library?

**Comment by nelsonic** [comment]
@digvijay-upadhyay _thank you_ for opening this issue. 🤔 
it's a question we would like to know the answer to! ❓ 

perhaps the _best_ place ask it is: https://github.com/tachyons-css/tachyons/issues 💡 
where the Tachyons community is more active. 😉

**Comment by digvijay-upadhyay** [comment]
Sorry didn't realise it was the other repo, posted there, https://github.com/tachyons-css/tachyons/issues/556.

Closing this one.
