### ISSUE TITLE
Keep Track of View Count with Hits Badge

### ISSUE THREAD

**Issue by nelsonic** [dwyl/tachyons-bootstrap#65]
Adding these lines of HTML to the `index.html` file:
```html
<a href="http://hits.dwyl.io/dwyl/tachyons-bootstrap">
  <img src="http://hits.dwyl.io/dwyl/tachyons-bootstrap.svg"
    alt="Hit Count" style="max-width:100%; height:1.7em;">
</a>
```
Given that this is a website, we cannot use markdown hence the HTML version...

We get:
![image](https://user-images.githubusercontent.com/194400/57183300-9c723b00-6ea2-11e9-8552-6bf5ba3326d4.png)

And very soon we will have _detailed_ stats for who is finding this project useful. 📈 
https://github.com/dwyl/hits/issues/66

**Comment by iteles** [comment]
Live:
![image](https://user-images.githubusercontent.com/4185328/57194119-db53cf80-6f3a-11e9-8465-a1aa6de8ef59.png)

Refreshed and got `2`, all working 👍
